---
# handlers file for ansible-splunk-forwarder
- name: reset failed splunkforwarder service
  shell: 'systemctl reset-failed SplunkForwarder.service'

- name: stop splunk
  command: '/opt/splunkforwarder/bin/splunk stop'
  args:
    warn: true

- name: restart splunk
  service:
    name: SplunkForwarder.service
    state: restarted 
    enabled: yes 
  
